# Generated by Django 4.2 on 2025-06-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_sellhouse',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
