# Generated by Django 4.2 on 2025-06-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_renthouse_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_renthouse',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='add_sellhouse',
            name='mobile',
        ),
    ]
